### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remote' of undefined

### ISSUE THREAD

**Issue by nuts3745** [ics-creative/150819_electron_editor#3]
### 問題の内容
`Uncaught TypeError: Cannot read property 'remote' of undefined`
というエラーでスクリプトが動作しない。

### 実行環境
- macOS 10.14.6
- node 10.15.1
- electron 6.4.1

### 期待する動作
`remote`が動作すること。

### 修正したこと
`main.js`で`nodeIntegration`をオンにしたら動作した。

```main.js
function createWindow() {
    // メインウィンドウを作成します
    mainWindow = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true
        },
        width: 800,
        height: 540
    });
```

**Comment by ics-ikeda** [comment]
お返事がかなり遅くなり申し訳ありませんでした。
ご指摘頂きましてありがとうございました。

Electronのレンダラープロセス側で `require("electron").remote` が参照できない件は、プリロードスクリプトを介して呼び出す形でメンテナンス修正しました。

こちらの件は解消したと思いますので、Issueはとじさせてください。
